#!/bin/bash

set -e

usage() {
    echo "Usage: $0 up|down|restart (-p aws-profile)? (-r aws-region)? system-name" >&2
    exit -1
}

# Gets the gateway instance id for the system
# Exits if gateway instance not found
# Arguments:
#   system - required
#   region arg - optional
#   profile command - optional
# Returns:
#   instance id
gateway_id() {
    local system=$1
    local region_arg=$2
    local profile_command=$3
    local gateway_id
    gateway_id=$(aws ec2 describe-instances $region_arg --filters Name=tag:Name,Values=${system}-bastion Name=instance-state-name,Values=running --query Reservations[0].Instances[0].InstanceId --output text $profile_command)
    if [ "$?" -ne 0 ] || [ "${gateway_id}" == None ]; then
        echo "Gateway not found, make sure gateway is running." >&2
        exit 1
    fi
    echo $gateway_id
}


# Returns the gateway asg for the system
# Exits if gateway not found
# Arguments:
#   system - required
#   region arg - optional
#   profile command - optional
gateway_asg() {
    local system=$1
    local region_arg=$2
    local profile_command=$3
    local gateway_asg
    gateway_asg=$(aws autoscaling describe-tags $region_arg $profile_command --filters Name=value,Values=${system}-bastion --query Tags[0].ResourceId --output text)
    if [ "$?" -ne 0 ] || [ "${gateway_asg}" == None ]; then
        echo "Gateway ASG not found, make sure your system name and AWS creds are correct.." >&2
        exit 1
    fi

    echo $gateway_asg
}

# Sets the desired capacity of the gateway ASG to 0
# Exits if gateway not found
# Arguments:
#   system - required
#   region arg - optional
#   profile command - optional
down() {
    local system=$1
    local region_arg=$2
    local profile_command=$3

    local gateway_asg
    gateway_asg=$(gateway_asg $system "$region_arg" "$profile_command")
    if [ "$?" -ne 0 ]; then
        exit $?
    fi

    local gateway_id
    gateway_id=$(gateway_id $system "$region_arg" "$profile_command")
    if [ "$?" -ne 0 ]; then
        exit $?
    fi

    $(aws autoscaling update-auto-scaling-group $region_arg $profile_command --auto-scaling-group-name $gateway_asg --desired-capacity 0) >&2  || exit $?
    echo "Access Gateway is scheduled for termination" >&2
}

# Sets the desired capacity of the gateway ASG to 1
# Exits if gateway not found
# Arguments:
#   system - required
#   region arg - optional
#   profile command - optional
up() {
    local system=$1
    local region_arg=$2
    local profile_command=$3

    local gateway_asg
    gateway_asg=$(gateway_asg $system "$region_arg" "$profile_command")
    if [ "$?" -ne 0 ]; then
        exit $?
    fi

    $(aws autoscaling update-auto-scaling-group $region_arg $profile_command --auto-scaling-group-name $gateway_asg --desired-capacity 1) >&2 || exit $?
    echo "Access Gateway is starting, it may take up to a few minutes before it is available for establishing connections" >&2
}

# Sets the gateway instance to unhealthy
# Exits if gateway not found
# Arguments:
#   system - required
#   region arg - optional
#   profile command - optional

restart() {
    local system=$1
    local region_arg=$2
    local profile_command=$3
    local gateway_id
    gateway_id=$(gateway_id $system "$region_arg" "$profile_command")
    if [ "$?" -ne 0 ]; then
        exit $?
    fi

    $(aws autoscaling set-instance-health $region_arg $profile_command --instance-id ${gateway_id} --health-status Unhealthy --no-should-respect-grace-period) >&2 || exit $?
    echo "Access Gateway is restarting, it may take up to a few minutes before it is available for re-establishing connections" >&2
}

# parse params, set globals
POSITIONAL=()
while [ $# -gt 0 ]
do
    case "$1" in
        -p)
            PROFILE_COMMAND="--profile $2"
            shift 2
            ;;
        -r)
            REGION=$2
            shift 2
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done

set -- "${POSITIONAL[@]}"

if [ "$1" == "" ] || [ "$2" == "" ]; then
    usage $@
fi

SYSTEM=$2

if [ "$REGION" == "" ]; then
    REGION_ARG=
else
    REGION_ARG="--region $REGION"
fi

case "$1" in
    up)
        $(up $SYSTEM "$REGION_ARG" "$PROFILE_COMMAND")
        ;;
    down)
        $(down $SYSTEM "$REGION_ARG" "$PROFILE_COMMAND")
        ;;
    restart)
        $(restart $SYSTEM "$REGION_ARG" "$PROFILE_COMMAND")
        ;;
    *)
        usage
        ;;
esac
