#!/bin/sh
git clone https://github.com/Cognician/datomic-doc
git clone https://github.com/ComputeSoftware/datomic-client-memdb
git clone https://github.com/Datomic/codeq
git clone https://github.com/Datomic/codeq
git clone https://github.com/Datomic/datomic-groovy-examples
git clone https://github.com/Datomic/datomic-java-examples
git clone https://github.com/Datomic/day-of-datomic
git clone https://github.com/JarrodCTaylor/schema-cartographer
git clone https://github.com/JarrodCTaylor/schema-cartographer
git clone https://github.com/JarrodCTaylor/schema-cartographer
git clone https://github.com/MageMasher/ion-web
git clone https://github.com/Provisdom/spectomic
git clone https://github.com/Provisdom/spectomic
git clone https://github.com/RallySoftware/datomic-replication
git clone https://github.com/SparkFund/spec-tacular
git clone https://github.com/TheLadders/sqlium
git clone https://github.com/WormBase/pseudoace
git clone https://github.com/Yuppiechef/cqrs-server
git clone https://github.com/Yuppiechef/cqrs-server
git clone https://github.com/Yuppiechef/datomic-schema
git clone https://github.com/a2ndrade/datomic-schema
git clone https://github.com/alexander-yakushev/clj-vagrant-template
git clone https://github.com/alexanderkiel/datomic-free
git clone https://github.com/alura-cursos/datomic-introducao
git clone https://github.com/arohner/datomic-compound-index
git clone https://github.com/avescodes/conformity
git clone https://github.com/avescodes/conformity
git clone https://github.com/avodonosov/datomic-helpers
git clone https://github.com/benkamphaus/datomic-basics
git clone https://github.com/bitemyapp/brambling
git clone https://github.com/bostonaholic/datomic-export
git clone https://github.com/brandonbloom/jseg
git clone https://github.com/cldwalker/datomic-box
git clone https://github.com/cldwalker/datomic-free
git clone https://github.com/cldwalker/datomico
git clone https://github.com/clj-nakano/datomic-cloud-primer
git clone https://github.com/clj-nakano/datomic-cloud-primer
git clone https://github.com/clojurecademy/clojurecademy
git clone https://github.com/cndreisbach/datomic-sinatra-wiki
git clone https://github.com/cognitect-labs/day-of-datomic-cloud
git clone https://github.com/csm/datomic-client-js
git clone https://github.com/dakra/datomic.el
git clone https://github.com/danscan/datomic-graphql
git clone https://github.com/datablend/datomic-back-to-the-future
git clone https://github.com/datablend/fluxgraph
git clone https://github.com/dazld/awesome-datomic
git clone https://github.com/democracyworks/datomic-toolbox
git clone https://github.com/dwhjames/datomic-ltl
git clone https://github.com/dwhjames/datomic-q-explain
git clone https://github.com/dwhjames/datomisca
git clone https://github.com/dwhjames/play-datomisca
git clone https://github.com/edubkendo/datomex
git clone https://github.com/eoliphan/valence
git clone https://github.com/espeed/dskel
git clone https://github.com/facjure/atomic
git clone https://github.com/favila/penelope
git clone https://github.com/felixflores/datomic_schema_grapher
git clone https://github.com/flyingmachine/datomic-booties
git clone https://github.com/flyingmachine/datomic-junk
git clone https://github.com/ftravers/datomic-tutorial
git clone https://github.com/fulcrologic/fulcro-rad-datomic
git clone https://github.com/fulcrologic/fulcro-rad-demo
git clone https://github.com/gns24/pydatomic
git clone https://github.com/gws/docker-datomic-free-transactor
git clone https://github.com/halgari/fafnir
git clone https://github.com/hden/reduxscript
git clone https://github.com/hlprmnky/ion-appsync-example
git clone https://github.com/hlprmnky/ion-appsync-example
git clone https://github.com/hodur-org/hodur-lacinia-datomic-adapter
git clone https://github.com/hyperfiddle/hyperfiddle
git clone https://github.com/jamesmartin/datomic-tutorial
git clone https://github.com/jdhollis/datomic-service
git clone https://github.com/jeffbrown/groovy-datomic
git clone https://github.com/jeffbrown/groovy-datomic
git clone https://github.com/jgdavey/kevin
git clone https://github.com/johnwayner/lein-datomic
git clone https://github.com/jsofra/datomic-rtree
git clone https://github.com/juxt/juxt-accounting
git clone https://github.com/juxt/pack-datomic
git clone https://github.com/kristianmandrup/datascript-tutorial
git clone https://github.com/lab-79/datomic-spec
git clone https://github.com/lab-79/dspec
git clone https://github.com/lab-79/dspec
git clone https://github.com/lambdaforge/datalog-parser
git clone https://github.com/lambdaisland/metabase-datomic
git clone https://github.com/limadelic/datomicjs
git clone https://github.com/loganmhb/cliodb
git clone https://github.com/madvas/todomvc-omnext-datomic-datascript
git clone https://github.com/magnars/datomic-snippets
git clone https://github.com/magnars/datomic-type-extensions
git clone https://github.com/metasoarous/datsync
git clone https://github.com/metasoarous/datsys
git clone https://github.com/metasoarous/datview
git clone https://github.com/metasoarous/tripl
git clone https://github.com/mozilla/mentat
git clone https://github.com/mrmcc3/tf_aws_datomic
git clone https://github.com/mtnygard/datoms-say-what
git clone https://github.com/mtnygard/simulant-example
git clone https://github.com/niamu/heroi.cc
git clone https://github.com/onyx-platform/onyx-commander-example
git clone https://github.com/onyx-platform/onyx-datomic
git clone https://github.com/pedestal/pedestal.ions
git clone https://github.com/philoskim/datomic-intro
git clone https://github.com/pointslope/docker-datomic
git clone https://github.com/pointslope/docker-datomic-console
git clone https://github.com/pointslope/docker-datomic-example
git clone https://github.com/quoll/kiara
git clone https://github.com/relevance/diametric
git clone https://github.com/robert-stuttaford/bridge
git clone https://github.com/rodnaph/lewis
git clone https://github.com/shaunxcode/datomicism
git clone https://github.com/smallhelm/level-fact-base
git clone https://github.com/tailrecursion/boot-datomic
git clone https://github.com/thebusby/datomic-tester
git clone https://github.com/thebusby/datomic-tester
git clone https://github.com/thegeez/clj-wiki
git clone https://github.com/tony-landis/datomic-py
git clone https://github.com/untangled-web/sql-datomic
git clone https://github.com/untangled-web/untangled-datomic
git clone https://github.com/upworthy/datomic-peer-svc
git clone https://github.com/viesti/ions-shopping-list
git clone https://github.com/vvvvalvalval/datofu
git clone https://github.com/waf/push-demo
git clone https://github.com/walkable-server/walkable
git clone https://github.com/wilkerlucio/pathom-datomic
git clone https://github.com/workframers/stillsuit
git clone https://github.com/yeller/datomic-riemann-reporter
git clone https://github.com/yeller/datomic-riemann-reporter
git clone https://github.com/zachallaun/datomic-cljs
git clone https://github.com/zololabs/demonic




git clone https://github.com/Provisdom/spectomic
git clone https://github.com/SparkFund/spec-tacular
git clone https://github.com/Yuppiechef/datomic-schema
git clone https://github.com/vvvvalvalval/datofu
git clone https://github.com/vvvvalvalval/datomock
git clone https://github.com/workco/umlaut
git clone https://github.com/zcaudate/spirit
