# Version format
version: git-{build}

# Skip Github tags
skip_tags: true

# VM Template
image: Visual Studio 2017

# Clone depth
clone_depth: 1

# Branches to clone
branches:
  only:
    - master

# Environment variables
environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
  VSVARSALLPATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
  matrix:
    - builder: msvc_ninja_64
      PYTHON: 'C:\\Python37-x64'
      BUILD_DIR: build
    - builder: msvc_ninja_32
      PYTHON: 'C:\\Python37'
      BUILD_DIR: build

# Required softwares for building
install:
  # Download required packages
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: if defined BUILD_DIR ( %PYTHON%\python.exe -m pip install meson )
  - cmd: if defined NINJA_URL ( powershell -Command wget %NINJA_URL% -OutFile ninja.zip && unzip ninja.zip )

# Build scripts
build_script:
  - cmd: if %builder% == msvc_ninja_64 ( call "%VSVARSALLPATH%" x64 && meson build && ninja -C build )
  - cmd: if %builder% == msvc_ninja_32 ( call "%VSVARSALLPATH%" x86 && meson build && ninja -C build )

## Artifacts
#artifacts:
#  - path: sdb.exe 

