#!/bin/bash
  cd `dirname $0`

  echo 'Installing: com.cognitect/rebl {:mvn/version "0.9.240"}'
  mvn -q org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=REBL-0.9.240/REBL-0.9.240.jar
  echo 'Installing: com.datomic/dev-local {:mvn/version "0.9.195"}'
  mvn -q org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=dev-local-0.9.195/dev-local-0.9.195.jar