language: ruby
#bundler_args: --without development
before_script: rake prepare
rvm:
  - 2.0.0
  - jruby-19mode

jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

script: INTEGRATION=true bundle exec rspec spec
