language: rust
jobs:
  include:
    - rust: 1.41.0
      env:
      - ALL=' '
    - rust: stable
      env:
        - CHECKFMT=1
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - BENCH=1
branches:
  only:
    - master
before_script:
  - |
      if [ "${CHECKFMT}" == "1"]; then
        rustup component add rustfmt --toolchain stable
      fi
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo test --verbose --no-default-features &&
      if [ "${CHECKFMT}" == "1"]; then
        cargo +stable fmt -- --check
      fi

