name: macOS x86_64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Detect Parameters
      id: detect-parameters
      run: |
        echo "::set-output name=radare_commit::$(git submodule status ext/radare2 | cut -f2 -d' ')"
        echo "::set-output name=radare_prefix::$(pwd)/ext/radare2/build/priv_install_dir"
        echo "::set-output name=qt_prefix::$(cd "$GITHUB_WORKSPACE/../" && pwd)/dist"
      shell: bash

    - name: Cache Radare
      id: cache-radare
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.radare_prefix }}
        key: radare-${{ steps.detect-parameters.outputs.radare_commit }}-macos-x86_64

    - name: Setup Python
      if: steps.cache-radare.outputs.cache-hit != 'true'
      uses: actions/setup-python@v2

    - name: Install Meson and Ninja
      if: steps.cache-radare.outputs.cache-hit != 'true'
      run: pip install meson ninja

    - name: Build Radare
      if: steps.cache-radare.outputs.cache-hit != 'true'
      run: |
        . tools/macos/activate-env
        tools/unix/build-radare

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.qt_prefix }}
        key: qt5-macos-x86_64

    - name: Build Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        . tools/macos/activate-env
        get-qt
        build-qt

    - name: Build Cryptoshark
      run: ./build

    - name: Package Cryptoshark
      run: |
        . tools/macos/activate-env
        mkdmg ../build-cryptoshark-x86_64

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-macos-x86_64
        prerelease: true
        title: Latest macOS Build for x86_64
        files: |
          ../build-cryptoshark-x86_64/*.dmg
