name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Build Dependencies
      run: |
        sudo apt-get install libatspi2.0-dev libgtk-3-dev libharfbuzz-dev '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libwayland-dev meson

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Detect Parameters
      id: detect-parameters
      run: |
        echo "::set-output name=radare_commit::$(git submodule status ext/radare2 | cut -f2 -d' ')"
        echo "::set-output name=radare_prefix::$(pwd)/ext/radare2/build/priv_install_dir"
        echo "::set-output name=qt_prefix::$(cd "$GITHUB_WORKSPACE/../" && pwd)/dist"
      shell: bash

    - name: Cache Radare
      id: cache-radare
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.radare_prefix }}
        key: radare-${{ steps.detect-parameters.outputs.radare_commit }}-ubuntu-20.04-x86_64

    - name: Build Radare
      if: steps.cache-radare.outputs.cache-hit != 'true'
      run: |
        . tools/linux/activate-env
        tools/unix/build-radare

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.qt_prefix }}
        key: qt5-ubuntu-20.04-x86_64

    - name: Build Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        . tools/linux/activate-env
        get-qt
        build-qt

    - name: Build Cryptoshark
      run: ./build

    - name: Package Cryptoshark
      run: ./tools/linux/mkdeb ../build-cryptoshark-x86_64

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-ubuntu-x86_64
        prerelease: true
        title: Latest Ubuntu 20.04 Build for x86_64
        files: |
          ../build-cryptoshark-x86_64/*.deb
