name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install 7-Zip PowerShell Module
      run: Install-Module 7Zip4PowerShell -Force -Verbose
      shell: powershell

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Detect Parameters
      id: detect-parameters
      run: |
        for /F "tokens=1" %%A in ('"git submodule status ext\radare2"') DO (
          echo ::set-output name=radare_commit::%%A
        )
        echo ::set-output name=radare_prefix::%cd%\ext\radare2\build\priv_install_dir
        cd ..
        echo ::set-output name=qt_prefix::%cd%\dist
      shell: cmd

    - name: Cache Radare
      id: cache-radare
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.radare_prefix }}
        key: radare-${{ steps.detect-parameters.outputs.radare_commit }}-windows-x86_64

    - name: Setup Python
      if: steps.cache-radare.outputs.cache-hit != 'true'
      uses: actions/setup-python@v2

    - name: Install Meson and Ninja
      if: steps.cache-radare.outputs.cache-hit != 'true'
      run: pip install meson ninja

    - name: Build Radare
      if: steps.cache-radare.outputs.cache-hit != 'true'
      run: |
        call tools\windows\activate-env x86_64
        call build-radare
      shell: cmd

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ steps.detect-parameters.outputs.qt_prefix }}
        key: qt5-windows-x86_64

    - name: Build Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        rmdir /s /q "%Programfiles%\dotnet"
        rmdir /s /q "%Programfiles%\Unity"
        call tools\windows\activate-env x86_64
        call get-qt
        call build-qt C:\build-qt
      shell: cmd

    - name: Build Cryptoshark
      run: build
      shell: cmd

    - name: Package Cryptoshark
      run: Compress-7Zip ..\build-cryptoshark-x86_64\app\release\cryptoshark.exe -ArchiveFileName "cryptoshark.zip" -Format Zip
      shell: powershell

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest-windows
        prerelease: true
        title: Latest Windows Build
        files: |
          cryptoshark.zip
